# Generated by Django 3.1.4 on 2021-08-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=450)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450)),
                ('vid_id', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-published_at'], name='fetch_api_v_publish_d44424_idx'),
        ),
        migrations.AddField(
            model_name='videmetadata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch_api.video'),
        ),
    ]
