# Generated by Django 3.2.6 on 2021-08-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450)),
                ('vid_id', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail_url', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_size', models.CharField(max_length=150)),
                ('thumbnail_url', models.CharField(max_length=450)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('current_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch_api.video')),
            ],
        ),
    ]
