# Generated by Django 3.1.4 on 2021-08-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videmetadata',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='videmetadata',
            old_name='video',
            new_name='current_video',
        ),
        migrations.RenameField(
            model_name='videmetadata',
            old_name='last_updated',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='videmetadata',
            old_name='screen_size',
            new_name='thumbnail_size',
        ),
        migrations.RenameField(
            model_name='videmetadata',
            old_name='url',
            new_name='thumbnail_url',
        ),
    ]
